package com.orule.rule.execution.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.Objects;

/**
 * 规则/规则集执行日志 JPA 实体（对应 RFC-0040 §3.3 execution_log 表）。
 *
 * <p>列名、约束、索引均与 §14.2 Flyway V1 一一对应：
 * <ul>
 *   <li>{@code uk_exec_task} UNIQUE — 在 task_id 上</li>
 *   <li>{@code ck_exec_type}   CHECK  — execution_type ∈ {RULE, RULE_SET}</li>
 *   <li>{@code ck_exec_status} CHECK  — status ∈ 5 个终态/中间态</li>
 * </ul>
 *
 * <p>H2 与 PostgreSQL 共用同一份 Java 代码（差异在 V1 SQL 解决）：
 * <ul>
 *   <li>H2：{@code BIGINT GENERATED BY DEFAULT AS IDENTITY} → {@link GenerationType#IDENTITY}</li>
 *   <li>PG：{@code BIGSERIAL}                              → {@link GenerationType#IDENTITY}</li>
 *   <li>H2：{@code CLOB}（input_context / output_context / error_message）→ {@link Column#columnDefinition} 显式</li>
 *   <li>PG：{@code JSONB}                                  → 同样以 CLOB 形式落地（Java 层通过 ObjectMapper 序列化，业务上等价 JSON）</li>
 * </ul>
 *
 * <p>JSON 字段全部用 {@code String} 存储，焦点是跨库兼容 + 单测容易。如果未来 PG JSONB 检索需求增长，
 * 可在 V2 引入 {@code @JdbcTypeCode(SqlTypes.JSON)}（Hibernate 6.2+），不影响本实体的核心 API。
 *
 * @see ExecutionLogRepository
 * @see ExecutionLogStatus
 * @see ExecutionType
 */
@Entity
@Table(name = "execution_log")
public class ExecutionLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** 任务 ID（UUID，业务方轮询键；唯一）。 */
    @Column(name = "task_id", nullable = false, unique = true, length = 64)
    private String taskId;

    /** 执行类型：RULE 同步单条 / RULE_SET 异步规则集。 */
    @Enumerated(EnumType.STRING)
    @Column(name = "execution_type", nullable = false, length = 16)
    private ExecutionType executionType;

    /** 关联 RuleType.programCode；RULE_SET 时为空。 */
    @Column(name = "rule_code", length = 128)
    private String ruleCode;

    /** 关联 RuleSetType.programCode；RULE 时为空。 */
    @Column(name = "rule_set_code", length = 128)
    private String ruleSetCode;

    /** 使用的执行器标识（JavaSourceExecutor / PythonExecutor 等）。 */
    @Column(name = "executor_type", nullable = false, length = 64)
    private String executorType;

    /** 当前状态：PENDING / RUNNING / SUCCESS / FAILED / PARTIAL_SUCCESS。 */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 16)
    private ExecutionLogStatus status;

    /**
     * 输入 ObjectInst 集合的 JSON 序列化（深拷贝）。
     * 列定义 {@code CLOB}（H2 与 PG 都接受；PG 的 CLOB 在字节流下与 TEXT 同效）。
     */
    @Column(name = "input_context", columnDefinition = "CLOB")
    private String inputContext;

    /**
     * 输出 ObjectInst 集合的 JSON 序列化（含规则修改后的累积状态）。
     */
    @Column(name = "output_context", columnDefinition = "CLOB")
    private String outputContext;

    /** RuleSet 总规则数；RULE 时为空。 */
    @Column(name = "total_count")
    private Integer totalCount;

    /** RuleSet 成功条数；RULE 时为空（默认 1 或 0）。 */
    @Column(name = "success_count")
    private Integer successCount;

    /** RuleSet 失败条数；RULE 时为空（默认 1 或 0）。 */
    @Column(name = "failed_count")
    private Integer failedCount;

    /** 错误码（§16.6，例如 EVAL_FAILED / RULE_NOT_FOUND）。 */
    @Column(name = "error_code", length = 64)
    private String errorCode;

    /** 错误详情（堆栈或人类可读消息）。 */
    @Column(name = "error_message", columnDefinition = "CLOB")
    private String errorMessage;

    /** 全链路追踪 ID（OpenTelemetry trace_id）。 */
    @Column(name = "trace_id", length = 64)
    private String traceId;

    /** 操作人 ID（来自 JWT，便于审计）。 */
    @Column(name = "operator_id", length = 64)
    private String operatorId;

    /** 多租户隔离字段。 */
    @Column(name = "tenant_id", length = 64)
    private String tenantId;

    /** 开始执行时刻（UTC）。 */
    @Column(name = "started_at")
    private Instant startedAt;

    /** 结束执行时刻（UTC）；PENDING 时为空。 */
    @Column(name = "finished_at")
    private Instant finishedAt;

    /** 总耗时（毫秒）；执行结束后回填。 */
    @Column(name = "duration_ms")
    private Long durationMs;

    /** 入库时刻（Java 层显式写入；由 Entity 创建时自动填充，Service 可覆写）。 */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    // === 工厂方法（§3.6 Service 层用法） ===

    /** PENDING 状态行：刚 submit 但尚未 start。 */
    public static ExecutionLog pending(String taskId, ExecutionType type,
                                       String ruleCode, String ruleSetCode,
                                       String executorType, String traceId,
                                       String operatorId, String tenantId) {
        ExecutionLog log = new ExecutionLog();
        log.taskId = Objects.requireNonNull(taskId, "taskId");
        log.executionType = Objects.requireNonNull(type, "executionType");
        log.ruleCode = ruleCode;
        log.ruleSetCode = ruleSetCode;
        log.executorType = Objects.requireNonNull(executorType, "executorType");
        log.status = ExecutionLogStatus.PENDING;
        log.traceId = traceId;
        log.operatorId = operatorId;
        log.tenantId = tenantId;
        log.createdAt = Instant.now();
        return log;
    }

    /**
     * 标记为开始执行：status → RUNNING，填充 started_at。
     * 仅允许从 PENDING 迁移。
     */
    public void markRunning() {
        if (this.status != ExecutionLogStatus.PENDING) {
            throw new IllegalStateException(
                    "Cannot markRunning from " + this.status + " (taskId=" + taskId + ")");
        }
        this.status = ExecutionLogStatus.RUNNING;
        this.startedAt = Instant.now();
    }

    /**
     * 标记为成功：status → SUCCESS，填充 finished_at / duration_ms。
     */
    public void markSuccess(String outputContextJson) {
        this.status = ExecutionLogStatus.SUCCESS;
        this.outputContext = outputContextJson;
        finalizeTiming();
    }

    /**
     * 标记为失败：status → FAILED，填充 finished_at / duration_ms / 错误码 / 错误详情。
     */
    public void markFailed(String errorCode, String errorMessage) {
        this.status = ExecutionLogStatus.FAILED;
        this.errorCode = errorCode;
        this.errorMessage = errorMessage;
        finalizeTiming();
    }

    /**
     * 标记为 RuleSet 部分成功：status → PARTIAL_SUCCESS。
     */
    public void markPartialSuccess(int total, int success, int failed,
                                   String outputContextJson) {
        this.status = ExecutionLogStatus.PARTIAL_SUCCESS;
        this.totalCount = total;
        this.successCount = success;
        this.failedCount = failed;
        this.outputContext = outputContextJson;
        finalizeTiming();
    }

    private void finalizeTiming() {
        Instant now = Instant.now();
        this.finishedAt = now;
        if (this.startedAt != null) {
            this.durationMs = now.toEpochMilli() - this.startedAt.toEpochMilli();
        }
    }

    // === Getters / Setters（受 JPA 规范约束必须存在） ===

    public Long getId() { return id; }
    public String getTaskId() { return taskId; }
    public void setTaskId(String taskId) { this.taskId = taskId; }
    public ExecutionType getExecutionType() { return executionType; }
    public void setExecutionType(ExecutionType executionType) { this.executionType = executionType; }
    public String getRuleCode() { return ruleCode; }
    public void setRuleCode(String ruleCode) { this.ruleCode = ruleCode; }
    public String getRuleSetCode() { return ruleSetCode; }
    public void setRuleSetCode(String ruleSetCode) { this.ruleSetCode = ruleSetCode; }
    public String getExecutorType() { return executorType; }
    public void setExecutorType(String executorType) { this.executorType = executorType; }
    public ExecutionLogStatus getStatus() { return status; }
    public void setStatus(ExecutionLogStatus status) { this.status = status; }
    public String getInputContext() { return inputContext; }
    public void setInputContext(String inputContext) { this.inputContext = inputContext; }
    public String getOutputContext() { return outputContext; }
    public void setOutputContext(String outputContext) { this.outputContext = outputContext; }
    public Integer getTotalCount() { return totalCount; }
    public void setTotalCount(Integer totalCount) { this.totalCount = totalCount; }
    public Integer getSuccessCount() { return successCount; }
    public void setSuccessCount(Integer successCount) { this.successCount = successCount; }
    public Integer getFailedCount() { return failedCount; }
    public void setFailedCount(Integer failedCount) { this.failedCount = failedCount; }
    public String getErrorCode() { return errorCode; }
    public void setErrorCode(String errorCode) { this.errorCode = errorCode; }
    public String getErrorMessage() { return errorMessage; }
    public void setErrorMessage(String errorMessage) { this.errorMessage = errorMessage; }
    public String getTraceId() { return traceId; }
    public void setTraceId(String traceId) { this.traceId = traceId; }
    public String getOperatorId() { return operatorId; }
    public void setOperatorId(String operatorId) { this.operatorId = operatorId; }
    public String getTenantId() { return tenantId; }
    public void setTenantId(String tenantId) { this.tenantId = tenantId; }
    public Instant getStartedAt() { return startedAt; }
    public void setStartedAt(Instant startedAt) { this.startedAt = startedAt; }
    public Instant getFinishedAt() { return finishedAt; }
    public void setFinishedAt(Instant finishedAt) { this.finishedAt = finishedAt; }
    public Long getDurationMs() { return durationMs; }
    public void setDurationMs(Long durationMs) { this.durationMs = durationMs; }
    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
