server:
  port: 8081

spring:
  application:
    name: orule-rule-execution-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.orule: INFO
