-- ============================================================
-- V1 (H2 in-memory / dev profile): 创建 execution_log 表
-- 文件路径: src/main/resources/db/migration/h2/V1__create_execution_log.sql
-- 参考:   RFC-0040 §3.3（H2 兼容版本；生产环境走 src/main/resources/db/migration/postgresql/V1）
--
-- 差异说明（H2 vs PostgreSQL）：
--   - BIGSERIAL        → BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY（SQL 标准；H2 PG 模式 + PG 14+ 通用）
--   - JSONB            → CLOB（H2 没有原生 JSONB，单测用 JSON 字符串等价存储）
--   - TIMESTAMP WITH TIME ZONE → TIMESTAMP（H2 默认时区本地化）
--   - COMMENT ON       → 注释（Flyway H2 解析不识别 COMMENT ON，故写在文件头）
--   - 不支持 IF NOT EXISTS 对 INDEX 用 IF NOT EXISTS（H2 v2 支持，OK）
--   - DESC 索引在 H2 上等价于升序（H2 自动选择升序扫描，行为兼容）
-- ============================================================

CREATE TABLE IF NOT EXISTS execution_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id         VARCHAR(64) NOT NULL,
    execution_type  VARCHAR(16) NOT NULL,
    rule_code       VARCHAR(128),
    rule_set_code   VARCHAR(128),
    executor_type   VARCHAR(64) NOT NULL,
    status          VARCHAR(16) NOT NULL,
    input_context   CLOB,
    output_context  CLOB,
    total_count     INT,
    success_count   INT,
    failed_count    INT,
    error_code      VARCHAR(64),
    error_message   CLOB,
    trace_id        VARCHAR(64),
    operator_id     VARCHAR(64),
    tenant_id       VARCHAR(64),
    started_at      TIMESTAMP,
    finished_at     TIMESTAMP,
    duration_ms     BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_exec_task   UNIQUE (task_id),
    CONSTRAINT ck_exec_type   CHECK (execution_type IN ('RULE', 'RULE_SET')),
    CONSTRAINT ck_exec_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL_SUCCESS'))
);

CREATE INDEX IF NOT EXISTS idx_exec_task           ON execution_log(task_id);
CREATE INDEX IF NOT EXISTS idx_exec_rule_code      ON execution_log(rule_code);
CREATE INDEX IF NOT EXISTS idx_exec_rule_set_code  ON execution_log(rule_set_code);
CREATE INDEX IF NOT EXISTS idx_exec_tenant_created ON execution_log(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_exec_trace          ON execution_log(trace_id);
CREATE INDEX IF NOT EXISTS idx_exec_status_created ON execution_log(status, created_at);

-- 列级注释（H2 不支持 COMMENT ON COLUMN，由代码层 ExecutionLog Entity 的 Javadoc 承载语义）：
-- task_id         = 任务 ID（UUID），业务方轮询键
-- execution_type  = RULE 同步单条 / RULE_SET 异步规则集
-- status          = PENDING/RUNNING/SUCCESS/FAILED/PARTIAL_SUCCESS
-- input_context   = 输入 ObjectInst 集合（深拷贝）
-- output_context  = 输出 ObjectInst 集合（含规则修改后的累积状态）
